[package]
name = "rooms-server"
version = "0.1.0"
authors = ["Masahiro Yoshida <myoshida@aiming-inc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1"
futures = "0.3.0"